apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment Name
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    # App Name
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # App Name
        app: nginx
    spec:
      containers:
        # Container Name
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80