apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    # APP Name
    app: nginx
  ports:
    - protocol: TCP
      # Service Port
      port: 80
      # Container Port
      targetPort: 80
      # Node Port (Range portas altas)
      nodePort: 30080